#pragma config(Sensor, S1,     sensor_cor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          base,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          frente,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          pistao,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FRENTE 1
#define BAIXO 2
#define OPOSTO 5

#define GIRO 3
#define MEIO_GIRO 4
#define FINAL 5
#define HORARIO 1
#define ANTI -1

#define CANTO_MAIOR 0
#define CANTO_MENOR 2
#define CANTO_MEIO 3
#define MEIO 1

#define VELOCIDADE 100
#define INCLINACAO_FRENTE_INICIAL 63
#define INCLINACAO_FRENTE_FINAL 35
#define ANGULO_GIRO 90
#define DISTANCIA_PISTAO -76
#define POSICAO_INICIAL 0

#define	BAIXO_HORARIO 'B'
#define BAIXO_ANTI 'b'
#define GIRO_HORARIO 'G'
#define GIRO_ANTI 'g'
#define FRENTE_HORARIO 'F'
#define	FRENTE_ANTI 'f'

#define ESQ 1
#define DIR 2

#define P_MEIO_CIMA 0, 1
#define P_MEIO_ESQUERDA 1, 0
#define P_MEIO_DIREITA 1, 2
#define P_MEIO_MBAIXO 2, 1

#define AMARELO 1
#define BRANCO 2
#define VERMELHO 3
#define	LARANJA 4
#define	AZUL 5
#define	VERDE 6
#define VAZIO 0

#define PARAMETROS atual, frente, &arquivo
#define PARAMETROS_1 atual, frente, arquivo

typedef struct face{
		int matriz[3][3];
		struct face *cima;
		struct face *baixo;
		struct face *esquerda;
		struct face *direita;
		struct face *oposto;
}face;

void Mover(char tipo, int sentido, int quantidade, int sleep_time);
int PertenceIntervalo(int menor, int maior, int numero);
int CapturaCor(int posicao_peca);
void InicializarMotores();
void Scan(face *branco, face *amarelo, face *vermelho, face *laranja, face* azul, face* verde);
void mostraMatriz(int *matriz, string nome);


typedef struct posicao{
		int x;
		int y;
		int cor;
}posicao;

int total=0;

int CorFace(face *atual){
	 return atual->matriz[1][1];
}

void LinhaLinha(face *envia, int linhaEnvia, face *recebe, int linhaRecebe){
		int i;
		for(i=0; i<3; i++){
				recebe->matriz[linhaRecebe][i] = envia->matriz[linhaEnvia][i];
		}
}

void ColunaColuna(face *envia, int colunaEnvia, face *recebe, int colunaRecebe){
		int i;
		for(i=0; i<3; i++){
				recebe->matriz[i][colunaRecebe] = envia->matriz[i][colunaEnvia];
		}
}

void ColunaColunaInvertido(face *envia, int colunaEnvia, face *recebe, int colunaRecebe){
		int i, j=2;
		for(i=0; i<3; i++){
				recebe->matriz[i][colunaRecebe] = envia->matriz[j][colunaEnvia];
				j--;
		}
}

void LinhaColuna(face *envia, int linha, face *recebe, int coluna){
		int i;
		for(i=0; i<3; i++){
				 recebe->matriz[i][coluna] = envia->matriz[linha][i];
		}
}

void LinhaColunaInvertido(face *envia, int linha, face *recebe, int coluna){
		int i, j=2;
		for(i=0; i<3; i++){
				 recebe->matriz[i][coluna] = envia->matriz[linha][j];
				 j--;
		}
}

void ColunaLinha(face *envia, int coluna, face *recebe, int linha){
		int i;
		for(i=2; i>=0; i--){
				 recebe->matriz[linha][i] = envia->matriz[i][coluna];
		}
}

void ColunaLinhaInvertido(face *envia, int coluna, face *recebe, int linha){
		int i, j=2;
		for(i=0; i<3; i++){
				 recebe->matriz[linha][i] = envia->matriz[j][coluna];
				 j--;
		}
}

void RotacaoMatriz(face *atual, int sentido){
		face temp;
		LinhaLinha(atual, 0, temp, 0);

		if(sentido==HORARIO){
				ColunaLinhaInvertido(atual, 0, atual, 0);
				LinhaColuna(atual, 2, atual, 0);
				ColunaLinhaInvertido(atual, 2, atual, 2);
				LinhaColuna(temp, 0, atual, 2);
		}else{
				ColunaLinha(atual, 2, atual, 0);
				LinhaColunaInvertido(atual, 2, atual, 2);
				ColunaLinha(atual, 0, atual, 2);
				LinhaColunaInvertido(temp, 0, atual, 0);
		}
}

void RotacaoAmarelo(face *atual, int sentido){
		face temp;
		face *cima = atual->cima;
		face *baixo = atual->baixo;
		face *esquerda = atual->esquerda;
		face *direita = atual->direita;

		LinhaLinha(cima, 2, temp, 2);

		RotacaoMatriz(atual, sentido);

		if(sentido==HORARIO){
				LinhaLinha(esquerda, 2, cima, 2);
				LinhaLinha(baixo, 2, esquerda, 2);
				LinhaLinha(direita, 2, baixo, 2);
				LinhaLinha(temp, 2, direita, 2);
		}else{
				LinhaLinha(direita, 2, cima, 2);
				LinhaLinha(baixo, 2, direita, 2);
				LinhaLinha(esquerda, 2, baixo, 2);
				LinhaLinha(temp, 2, esquerda, 2);
		}
}

void RotacaoVerde(face *atual, int sentido){
		face temp;
		face *cima = atual->cima;
		face *baixo = atual->baixo;
		face *esquerda = atual->esquerda;
		face *direita = atual->direita;

		LinhaLinha(cima, 2, temp, 2);

		RotacaoMatriz(atual, sentido);

		if(sentido==HORARIO){
				ColunaLinhaInvertido(esquerda, 2, cima, 2);
				LinhaColuna(baixo, 0, esquerda, 2);
				ColunaLinhaInvertido(direita, 0, baixo, 0);
				LinhaColuna(temp, 2, direita, 0);
		}else{
				ColunaLinha(direita, 0, cima, 2);
				LinhaColunaInvertido(baixo, 0, direita, 0);
				ColunaLinha(esquerda, 2, baixo, 0);
				LinhaColunaInvertido(temp, 2, esquerda, 2);
		}
}

void RotacaoAzul(face *atual, int sentido){
		face temp;
		face *cima = atual->cima;
		face *baixo = atual->baixo;
		face *esquerda = atual->esquerda;
		face *direita = atual->direita;

		LinhaLinha(cima, 0, temp, 0);

		RotacaoMatriz(atual, sentido);

		if(sentido==HORARIO){
				ColunaLinha(esquerda, 2, cima, 0);
				LinhaColunaInvertido(baixo, 2, esquerda, 2);
				ColunaLinha(direita, 0, baixo, 2);
				LinhaColunaInvertido(temp, 0, direita, 0);
		}else{
				ColunaLinhaInvertido(direita, 0, cima, 0);
				LinhaColuna(baixo, 2, direita, 0);
				ColunaLinhaInvertido(esquerda, 2, baixo, 2);
				LinhaColuna(temp, 0, esquerda, 2);
		}
}

void RotacaoVermelho(face *atual, int sentido){
		face temp;
		face *cima = atual->cima;
		face *baixo = atual->baixo;
		face *esquerda = atual->esquerda;
		face *direita = atual->direita;

		ColunaColuna(cima, 2, temp, 2);

		RotacaoMatriz(atual, sentido);

		if(sentido==HORARIO){
				ColunaColuna(esquerda, 2, cima, 2);
				ColunaColuna(baixo, 2, esquerda, 2);
				ColunaColunaInvertido(direita, 0, baixo, 2);
				ColunaColunaInvertido(temp, 2, direita, 0);
		}else{
				ColunaColunaInvertido(direita, 0, cima, 2);
				ColunaColunaInvertido(baixo, 2, direita, 0);
				ColunaColuna(esquerda, 2, baixo, 2);
				ColunaColuna(temp, 2, esquerda, 2);
		}
}

void RotacaoLaranja(face *atual, int sentido){
		face temp;
		face *cima = atual->cima;
		face *baixo = atual->baixo;
		face *esquerda = atual->esquerda;
		face *direita = atual->direita;

		ColunaColuna(cima, 0, temp, 0);

		RotacaoMatriz(atual, sentido);

		if(sentido==HORARIO){
				ColunaColunaInvertido(esquerda, 2, cima, 0);
				ColunaColunaInvertido(baixo, 0, esquerda, 2);
				ColunaColuna(direita, 0, baixo, 0);
				ColunaColuna(temp, 0, direita, 0);
		}else{
				ColunaColuna(direita, 0, cima, 0);
				ColunaColuna(baixo, 0, direita, 0);
				ColunaColunaInvertido(esquerda, 2, baixo, 0);
				ColunaColunaInvertido(temp, 0, esquerda, 2);
		}
}

void PreencheMatriz(int *matriz, int v1, int v2, int v3, int v4, int v5, int v6, int v7, int v8, int v9){
		int i=0;
		int valor[9];
		valor[0] = v1;
		valor[1] = v2;
		valor[2] = v3;
		valor[3] = v4;
		valor[4] = v5;
		valor[5] = v6;
		valor[6] = v7;
		valor[7] = v8;
		valor[8] = v9;
		int linha;
		int coluna;

		for(linha=0; linha<=2; linha++){
				for(coluna=0; coluna<=2; coluna++){
						matriz[linha*3 + coluna] = valor[i];
						i++;
				}
		}
}

void InterligarFaces(face *atual, face *cima, face *direita, face *baixo, face *esquerda, face *oposto){
		atual->cima = cima;
		atual->baixo = baixo;
		atual->esquerda = esquerda;
		atual->direita = direita;
		atual->oposto = oposto;
}

void InicializarFaces(face *branco, face *amarelo, face *vermelho, face *laranja, face *verde, face *azul){
		InterligarFaces(branco, azul, vermelho, verde, laranja, amarelo);
		InterligarFaces(vermelho, branco, azul, amarelo, verde, laranja);
		InterligarFaces(azul, branco, laranja, amarelo, vermelho, verde);
		InterligarFaces(laranja, branco, verde, amarelo, azul, vermelho);
		InterligarFaces(verde, branco, vermelho, amarelo, laranja, azul);
		InterligarFaces(amarelo, verde, vermelho, azul, laranja, branco);

		PreencheMatriz(branco->matriz, 6,3,5, 4,2,1, 1,1,1);
		PreencheMatriz(vermelho->matriz, 5,5,2, 1,3,1, 2,3,1);
		PreencheMatriz(azul->matriz, 3,6,3, 6,5,5, 4,2,6);
		PreencheMatriz(laranja->matriz, 2,6,5, 4,4,5, 4,3,6);
		PreencheMatriz(verde->matriz, 3,4,4, 2,6,3, 3,2,5);
		PreencheMatriz(amarelo->matriz, 1,4,4, 5,1,2, 2,6,6);
}

void PermiteEscrita(long *codigo, char *movimentos){
		*codigo = fileOpenWrite(movimentos);
}

void PermiteLeitura(long *codigo, char *movimentos){
		*codigo = fileOpenRead(movimentos);
}

void EncerraEscritaLeitura(long *codigo){
		fileClose(*codigo);
}

void LerMovimento(long *codigo){
		char valorLido;
		int cont=0;

		while (fileReadChar(*codigo, &valorLido)){
	    	switch(valorLido){
	    			case BAIXO_HORARIO:
	    					Mover(BAIXO, ANTI, 1, 0);
	    					break;
						case BAIXO_ANTI:
								Mover(BAIXO, HORARIO, 1, 0);
	    					break;
						case GIRO_HORARIO:
								Mover(GIRO, HORARIO, 1, 0);
	    					break;
						case GIRO_ANTI:
								Mover(GIRO, ANTI, 1, 0);
	    					break;
						case FRENTE_HORARIO:
								Mover(FRENTE, HORARIO, 1, 0);
	    					break;
						case FRENTE_ANTI:
								Mover(FRENTE, ANTI, 1, 0);
	    					break;
	  		}
	  		writeDebugStreamLine("#%d Movimento: %c", ++cont, valorLido);
	  }
}

void EscreveMovimento(long *arquivo, char tipo){
		fileWriteChar(*arquivo, tipo);
		total++;
}

void AlinhaFrente(face *atual, face *&frente, long *arquivo){
		if(CorFace(frente)!=(CorFace(atual))){
				if(CorFace(frente->esquerda) == CorFace(atual)){
						EscreveMovimento(arquivo, GIRO_ANTI);
				}else if(CorFace(frente->direita) == CorFace(atual)){
						EscreveMovimento(arquivo, GIRO_HORARIO);
				}else{
						EscreveMovimento(arquivo, GIRO_ANTI);
						EscreveMovimento(arquivo, GIRO_ANTI);
				}
				frente = atual;
		}
}

void Esquerda(int sentido, face *atual, face *&frente, long *arquivo){
		switch(CorFace(atual->esquerda)){
				case VERDE:
						RotacaoVerde(atual->esquerda, sentido);
						break;
				case AZUL:
						RotacaoAzul(atual->esquerda, sentido);
						break;
				case VERMELHO:
						RotacaoVermelho(atual->esquerda, sentido);
						break;
				case LARANJA:
						RotacaoLaranja(atual->esquerda, sentido);
						break;
		}
		AlinhaFrente(atual->esquerda, frente, arquivo);
		if(sentido==HORARIO)
				EscreveMovimento(arquivo, FRENTE_HORARIO);
		else
				EscreveMovimento(arquivo, FRENTE_ANTI);
}

void Direita(int sentido, face *atual, face *&frente, long *arquivo){
		switch(CorFace(atual->direita)){
				case VERDE:
						RotacaoVerde(atual->direita, sentido);
						break;
				case AZUL:
						RotacaoAzul(atual->direita, sentido);
						break;
				case VERMELHO:
						RotacaoVermelho(atual->direita, sentido);
						break;
				case LARANJA:
						RotacaoLaranja(atual->direita, sentido);
						break;
		}
		AlinhaFrente(atual->direita, frente, arquivo);
		if(sentido==HORARIO)
				EscreveMovimento(arquivo, FRENTE_HORARIO);
		else
				EscreveMovimento(arquivo, FRENTE_ANTI);
}

void Baixo(int sentido, face *atual, face *&frente, long *arquivo){

		switch(CorFace(atual->baixo)){
				case VERDE:
						RotacaoVerde(atual->baixo, sentido);
						break;
				case AZUL:
						RotacaoAzul(atual->baixo, sentido);
						break;
				case VERMELHO:
						RotacaoVermelho(atual->baixo, sentido);
						break;
				case LARANJA:
						RotacaoLaranja(atual->baixo, sentido);
						break;
				case AMARELO:
						RotacaoAmarelo(atual->baixo, sentido);
						break;
		}
		if(CorFace(atual->baixo)!=AMARELO){
				AlinhaFrente(atual->baixo, frente, arquivo);
				if(sentido==HORARIO)
						EscreveMovimento(arquivo, FRENTE_HORARIO);
				else
						EscreveMovimento(arquivo, FRENTE_ANTI);
		}else{
				if(sentido==HORARIO)
						EscreveMovimento(arquivo, BAIXO_HORARIO);
				else
						EscreveMovimento(arquivo, BAIXO_ANTI);
		}
}

void Cima(int sentido, face *atual, face *&frente, long *arquivo){
		switch(CorFace(atual->cima)){
				case VERDE:
						RotacaoVerde(atual->cima, sentido);
						break;
				case AZUL:
						RotacaoAzul(atual->cima, sentido);
						break;
				case VERMELHO:
						RotacaoVermelho(atual->cima, sentido);
						break;
				case LARANJA:
						RotacaoLaranja(atual->cima, sentido);
						break;
		}

		AlinhaFrente(atual->cima, frente, arquivo);
		if(sentido==HORARIO)
				EscreveMovimento(arquivo, FRENTE_HORARIO);
		else
				EscreveMovimento(arquivo, FRENTE_ANTI);
}

void Frente(int sentido, face *atual, face *&frente, long *arquivo){
		switch(CorFace(atual)){
				case VERDE:
						RotacaoVerde(atual, sentido);
						break;
				case AZUL:
						RotacaoAzul(atual, sentido);
						break;
				case VERMELHO:
						RotacaoVermelho(atual, sentido);
						break;
				case LARANJA:
						RotacaoLaranja(atual, sentido);
						break;
				case AMARELO:
						RotacaoAmarelo(atual, sentido);
						break;
				}
				if(CorFace(atual)!=AMARELO){
								AlinhaFrente(atual, frente, arquivo);
						if(sentido==HORARIO){
								EscreveMovimento(arquivo, FRENTE_HORARIO);
						}else{
								EscreveMovimento(arquivo, FRENTE_ANTI);
						}
				}else{
						if(sentido==HORARIO){
								EscreveMovimento(arquivo, BAIXO_HORARIO);
						}else{
								EscreveMovimento(arquivo, BAIXO_ANTI);
						}
				}
}

void Tras(int sentido, face *atual, face *&frente, long *arquivo){
		switch(CorFace(atual->oposto)){
				case VERDE:
						RotacaoVerde(atual->oposto, sentido);
						break;
				case AZUL:
						RotacaoAzul(atual->oposto, sentido);
						break;
				case VERMELHO:
						RotacaoVermelho(atual->oposto, sentido);
						break;
				case LARANJA:
						RotacaoLaranja(atual->oposto, sentido);
						break;
				case AMARELO:
						RotacaoAmarelo(atual->oposto, sentido);
						break;
				}
				if(CorFace(atual->oposto)!=AMARELO){
					  AlinhaFrente(atual->oposto, frente, arquivo);
				if(sentido==HORARIO)
						EscreveMovimento(arquivo, FRENTE_HORARIO);
				else
						EscreveMovimento(arquivo, FRENTE_ANTI);
		}else{
				if(sentido==HORARIO)
						EscreveMovimento(arquivo, BAIXO_HORARIO);
				else
						EscreveMovimento(arquivo, BAIXO_ANTI);
		}
}

void AvancaFace(face *&atual, int tipo, int sentido){
		if(tipo==6){
				switch(CorFace(atual)){
						case BRANCO:
								atual = atual->baixo;
								break;
						case VERDE:
								atual = atual->direita;
								break;
						case AZUL:
								atual = atual->direita;
								break;
						case VERMELHO:
								atual = atual->direita;
								break;
						case LARANJA:
								atual = atual->baixo;
								break;
						case AMARELO:
								atual = atual->oposto;
								break;
				}
		}else{
				if(sentido==ESQ){
						switch(CorFace(atual)){
								case VERDE:
										atual = atual->esquerda;
										break;
								case AZUL:
										atual = atual->esquerda;
										break;
								case VERMELHO:
										atual = atual->esquerda;
										break;
								case LARANJA:
										atual = atual->esquerda;
										break;
						}
				}else{
						switch(CorFace(atual)){
								case VERDE:
										atual = atual->direita;
										break;
								case AZUL:
										atual = atual->direita;
										break;
								case VERMELHO:
										atual = atual->direita;
										break;
								case LARANJA:
										atual = atual->direita;
										break;
						}
				}
		}
}

int VerificaCor(face *atual, int linha, int coluna, int cor){
		return atual->matriz[linha][coluna] == cor;
}
int Camada2(face *atual){
		if(VerificaCor(atual, 1, 0, CorFace(atual)) &&
			VerificaCor(atual, 1, 2, CorFace(atual)) &&
			VerificaCor(atual->esquerda, 1, 0, CorFace(atual->esquerda)) &&
			VerificaCor(atual->esquerda, 1, 2, CorFace(atual->esquerda)) &&
			VerificaCor(atual->direita, 1, 0, CorFace(atual->direita)) &&
			VerificaCor(atual->direita, 1, 2, CorFace(atual->direita)) &&
			VerificaCor(atual->oposto, 1, 0, CorFace(atual->oposto)) &&
			VerificaCor(atual->oposto, 1, 2, CorFace(atual->oposto)))
					return 1;
			else
					return 0;
}

int Camada3(face *atual){
		if(VerificaCor(atual, 2, 0, atual->matriz[2][2]) &&
			VerificaCor(atual, 2, 1, atual->matriz[2][2]) &&
			VerificaCor(atual, 2, 2, atual->matriz[2][2]) &&
			VerificaCor(atual->esquerda, 2, 0, atual->esquerda->matriz[2][2]) &&
			VerificaCor(atual->esquerda, 2, 2, atual->esquerda->matriz[2][2]) &&
			VerificaCor(atual->direita, 2, 0, atual->direita->matriz[2][2]) &&
			VerificaCor(atual->direita, 2, 2, atual->direita->matriz[2][2]) &&
			VerificaCor(atual->oposto, 2, 0, atual->oposto->matriz[2][2]) &&
			VerificaCor(atual->oposto, 2, 2, atual->oposto->matriz[2][2])){
					return 1;
			}else{
					return 0;
			}
}

int MeiosIguais(face *atual){
		if(VerificaCor(atual, 2, 0, atual->matriz[2][1]) &&
			 (VerificaCor(atual, 2, 1, atual->matriz[2][2])) &&
			 (VerificaCor(atual->oposto, 2, 0, atual->oposto->matriz[2][1])) &&
			 (VerificaCor(atual->oposto, 2, 1, atual->oposto->matriz[2][2])))
			   return 1;
		else
			return 0;
}


int Cruz(face *atual, int cor){
		if(atual->matriz[0][1] == cor &&
		 	 atual->matriz[1][0] == cor &&
		   atual->matriz[2][1] == cor &&
			 atual->matriz[1][2] == cor){
					if(CorFace(atual) == BRANCO){
							if(atual->baixo->matriz[0][1] == CorFace(atual->baixo)&&
			 					 atual->cima->matriz[0][1] == CorFace(atual->cima) &&
			 			   	 atual->esquerda->matriz[0][1] == CorFace(atual->esquerda) &&
			 				 	 atual->direita->matriz[0][1] == CorFace(atual->direita))
							 	 return 1;
							else
								 return 0;
					}
			return 1;
		  }
return 0;
}

int Cantos(face *atual, int cor){
    if(VerificaCor(atual, 0, 0, cor) &&
			 VerificaCor(atual, 0, 2, cor) &&
			 VerificaCor(atual, 2, 0, cor) &&
			 VerificaCor(atual, 2, 2, cor)){
			 		if(CorFace(atual)==BRANCO){
			 				if(VerificaCor(atual->baixo, 0, 0, CorFace(atual->baixo)) &&
			 					 VerificaCor(atual->baixo, 0, 1, CorFace(atual->baixo)) &&
			 					 VerificaCor(atual->baixo, 0, 2, CorFace(atual->baixo)) &&
			 					 VerificaCor(atual->esquerda, 0, 0, CorFace(atual->esquerda)) &&
			 					 VerificaCor(atual->esquerda, 0, 1, CorFace(atual->esquerda)) &&
			 					 VerificaCor(atual->esquerda, 0, 2, CorFace(atual->esquerda)) &&
			 					 VerificaCor(atual->direita, 0, 0, CorFace(atual->direita)) &&
			 					 VerificaCor(atual->direita, 0, 1, CorFace(atual->direita)) &&
			 					 VerificaCor(atual->direita, 0, 2, CorFace(atual->direita)) &&
			 					 VerificaCor(atual->cima, 0, 0, CorFace(atual->cima)) &&
			 					 VerificaCor(atual->cima, 0, 1, CorFace(atual->cima)) &&
			 					 VerificaCor(atual->cima, 0, 2, CorFace(atual->cima)))
			 					   return 1;
			 				else{
			 					return 0;
			 				}
			 		}else{
			 				return 1;
			 		}
			}
		else
			 return 0;
}

int QuantidadeCantos(face *atual, int cor){
		int cont=0;
		if(VerificaCor(atual, 0, 0, cor))
				cont++;
		if(VerificaCor(atual, 0, 2, cor))
				cont++;
		if(VerificaCor(atual, 2, 0, cor))
				cont++;
		if(VerificaCor(atual, 2, 2, cor))
				cont++;
		return cont;
}

void MostraTodasMatrizes(face vermelho, face laranja, face verde, face azul, face branco, face amarelo){
		string nome;
		writeDebugStreamLine("\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/");
		nome = "Vermelho";
		mostraMatriz(vermelho.matriz, nome);
		nome = "Azul";
		mostraMatriz(azul.matriz, nome);
		nome = "Laranja";
		mostraMatriz(laranja.matriz, nome);
		nome = "Verde";
		mostraMatriz(verde.matriz, nome);
		nome = "Amarelo";
		mostraMatriz(amarelo.matriz, nome);
		nome = "Branco";
		mostraMatriz(branco.matriz, nome);
		writeDebugStreamLine("/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/");
}
void SequenciaCamada2(int sentido, face *atual, face *&frente, long *arquivo){
		if(sentido==ESQ){
				Baixo(HORARIO, PARAMETROS_1);
				Esquerda(HORARIO, PARAMETROS_1);
				Baixo(HORARIO, PARAMETROS_1);
				Esquerda(ANTI, PARAMETROS_1);
				Baixo(ANTI, PARAMETROS_1);
				Frente(ANTI, PARAMETROS_1);
				Baixo(ANTI, PARAMETROS_1);
				Frente(HORARIO, PARAMETROS_1);
		}else{
				Baixo(ANTI, PARAMETROS_1);
				Direita(ANTI, PARAMETROS_1);
				Baixo(ANTI, PARAMETROS_1);
				Direita(HORARIO, PARAMETROS_1);
				Baixo(HORARIO, PARAMETROS_1);
				Frente(HORARIO, PARAMETROS_1);
				Baixo(HORARIO, PARAMETROS_1);
				Frente(ANTI, PARAMETROS_1);
		}
}

void SequenciaCruzAmarelo(face *atual, face *&frente, long *arquivo){
			Frente(HORARIO, PARAMETROS_1);
			Baixo(HORARIO, PARAMETROS_1);
			Esquerda(HORARIO, PARAMETROS_1);
			Baixo(ANTI, PARAMETROS_1);
			Esquerda(ANTI, PARAMETROS_1);
			Frente(ANTI, PARAMETROS_1);
}

void SequenciaCantosAmarelo(face *atual, face *&frente, long *arquivo){
		Esquerda(HORARIO, PARAMETROS_1);
		Baixo(HORARIO, PARAMETROS_1);
		Esquerda(ANTI, PARAMETROS_1);
		Baixo(HORARIO, PARAMETROS_1);
		Esquerda(HORARIO, PARAMETROS_1);
		Baixo(HORARIO, PARAMETROS_1);
		Baixo(HORARIO, PARAMETROS_1);
		Esquerda(ANTI, PARAMETROS_1);
}
void SequenciaL(face *atual, face *&frente, long *arquivo){
		Esquerda(ANTI, PARAMETROS_1);
		Frente(HORARIO, PARAMETROS_1);
		Esquerda(ANTI, PARAMETROS_1);
		Tras(HORARIO, PARAMETROS_1);
		Tras(HORARIO, PARAMETROS_1);
		Esquerda(HORARIO, PARAMETROS_1);
		Frente(ANTI, PARAMETROS_1);
		Esquerda(ANTI, PARAMETROS_1);
		Tras(HORARIO, PARAMETROS_1);
		Tras(HORARIO, PARAMETROS_1);
		Esquerda(HORARIO, PARAMETROS_1);
		Esquerda(HORARIO, PARAMETROS_1);
}

void SequenciaTrocaFinal(face *atual, face *&frente, long *arquivo){
		int sentido=0;
		Frente(HORARIO, PARAMETROS_1);
		Frente(HORARIO, PARAMETROS_1);
		if(VerificaCor(atual->esquerda, 2, 1, CorFace(atual))){
				Baixo(HORARIO, PARAMETROS_1);
		}else{
				Baixo(ANTI, PARAMETROS_1);
				sentido = 1;
		}
		Esquerda(ANTI, PARAMETROS_1);
		Direita(HORARIO, PARAMETROS_1);
		Frente(HORARIO, PARAMETROS_1);
		Frente(HORARIO, PARAMETROS_1);
		Esquerda(HORARIO, PARAMETROS_1);
		Direita(ANTI, PARAMETROS_1);
		if(sentido==0){
				Baixo(HORARIO, PARAMETROS_1);
		}else{
				Baixo(ANTI, PARAMETROS_1);
		}
		Frente(ANTI, PARAMETROS_1);
		Frente(ANTI, PARAMETROS_1);
}


task main(){
		face branco;
		face amarelo;
		face vermelho;
		face laranja;
		face azul;
		face verde;

		face *atual;
		face *frente;
clearDebugStream();
		InicializarMotores();
		InicializarFaces(&branco, &amarelo, &vermelho, &laranja, &verde, &azul)

		MostraTodasMatrizes(vermelho, laranja, verde, azul, branco, amarelo);

		int i;


		char *movimentos = "Movimentos";
		long arquivo;

		PermiteEscrita(&arquivo, movimentos);

		atual = &branco;
		frente = &vermelho;
		MostraTodasMatrizes(vermelho, laranja, verde, azul, branco, amarelo);


				//1° PASSO - CRUZ

		int j;
		int moduloI;
		int moduloJ;
		int cont;
		int encontrado;

		writeDebugStreamLine("passo 1");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);

		while(!Cruz(branco, BRANCO)){
				while(!Cruz(amarelo, BRANCO)){
						j = 2;
						for(i=-1; i<3; i++){

								moduloI = abs(i);
								moduloJ = abs(j);

								if((VerificaCor(atual, moduloI, moduloJ, BRANCO))){
										switch(CorFace(atual)){
												case BRANCO:
														if(moduloI==1){			//1,2 0,1 1,0 2,1
																while(VerificaCor(atual->oposto, moduloI, moduloJ, BRANCO)){
																		Tras(HORARIO, PARAMETROS);
																}
																if(moduloJ==2){
																		Direita(HORARIO, PARAMETROS);
																		Direita(HORARIO, PARAMETROS);
																}else{
																		Esquerda(HORARIO, PARAMETROS);
																		Esquerda(HORARIO, PARAMETROS);
																}
														}else{
																while(VerificaCor(atual->oposto, abs(moduloI-2), moduloJ, BRANCO)){
																		Tras(HORARIO, PARAMETROS);
																}
																if(moduloI==0){
																		Cima(HORARIO, PARAMETROS);
																		Cima(HORARIO, PARAMETROS);
																}else{
																		Baixo(HORARIO, PARAMETROS);
																		Baixo(HORARIO, PARAMETROS);
																}
														}
														break;
												case AZUL:
														if(moduloI==1){
																while(VerificaCor(atual->baixo, moduloI, abs(ModuloJ-2), BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																if(moduloJ==2){
																		Direita(ANTI, PARAMETROS);
																}else{
																		Esquerda(HORARIO, PARAMETROS);
																}
														}else{
																while(VerificaCor(atual->baixo, 2, 1, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																Frente(HORARIO, PARAMETROS);
																i = -1;
																j = 2;
														}
														break;
												case VERMELHO:
														if(moduloI==1){
																while(VerificaCor(atual->baixo, moduloJ, moduloI, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																if(moduloJ==2){
																		Direita(ANTI, PARAMETROS);
																}else{
																		Esquerda(HORARIO, PARAMETROS);
																}
														}else{
																while(VerificaCor(atual->baixo, 1, 2, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																Frente(HORARIO, PARAMETROS);
																i = -1;
																j = 2;
														}
														break;
												case VERDE:
														if(moduloI==1){
																while(VerificaCor(atual->baixo, moduloI, moduloJ, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																if(moduloJ==2){
																		Direita(ANTI, PARAMETROS);
																}else{
																		Esquerda(HORARIO, PARAMETROS);
																}
														}else{
																while(VerificaCor(atual->baixo, 0, 1, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																Frente(HORARIO, PARAMETROS);
																i = -1;
																j = 2;
														}
														break;
												case LARANJA:
														if(moduloI==1){
																while(VerificaCor(atual->baixo, abs(moduloJ-2), moduloI, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																if(moduloJ==2){
																		Direita(ANTI, PARAMETROS);
																}else{
																		Esquerda(HORARIO, PARAMETROS);
																}
														}else{
																while(VerificaCor(atual->baixo, 1, 0, BRANCO)){
																		Baixo(HORARIO, PARAMETROS);
																}
																Frente(HORARIO, PARAMETROS);
																i = -1;
																j = 2;
														}
														break;
										}
								}
						j--;
						}
						AvancaFace(atual, 6, ESQ);
				}
				atual = &vermelho;
				while(!Cruz(branco, BRANCO)){
						j=2;
						for(i=-1; i<3; i++){
								moduloI = abs(i);
								moduloJ = abs(j);
								while(!VerificaCor(atual, 2, 1, CorFace(atual)) || !VerificaCor(atual->baixo, moduloI, moduloJ, BRANCO)){
										Baixo(HORARIO, PARAMETROS);
								}
								Frente(HORARIO, PARAMETROS);
								Frente(HORARIO, PARAMETROS);
								AvancaFace(atual, 4, ESQ);
								j--;
						}
				}
		}

///2º PASSO - CANTOS DA CRUZ
		writeDebugStreamLine("passo 2");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);

		while(!Cantos(branco, BRANCO)){
				atual = &branco;
				encontrado=0;
				cont=0;
				if(VerificaCor(atual, 0, 0, BRANCO)){
						if(!VerificaCor(atual->cima, 0, 2, CorFace(atual->cima)) ||
						   !VerificaCor(atual->esquerda, 0, 0, CorFace(atual->esquerda))){
								Esquerda(ANTI, PARAMETROS);
								Tras(ANTI, PARAMETROS);
								Esquerda(HORARIO, PARAMETROS);
						}
				}

				if(VerificaCor(atual, 0, 2, BRANCO)){
						if(!VerificaCor(atual->cima, 0, 0, CorFace(atual->cima)) ||
						   !VerificaCor(atual->direita, 0, 2, CorFace(atual->direita))){
								Direita(HORARIO, PARAMETROS);
								Tras(HORARIO, PARAMETROS);
								Direita(ANTI, PARAMETROS);
						}
				}
				if(VerificaCor(branco, 2, 0, BRANCO)){
						if(!VerificaCor(atual->esquerda, 0, 2, CorFace(atual->esquerda)) ||
						   !VerificaCor(atual->baixo, 0, 0, CorFace(atual->baixo))){
								Esquerda(HORARIO, PARAMETROS);
								Tras(HORARIO, PARAMETROS);
								Esquerda(ANTI, PARAMETROS);
						}
				}

				if(VerificaCor(atual, 2, 2, BRANCO)){
						if(!VerificaCor(atual->baixo, 0, 2, CorFace(atual->baixo)) ||
						   !VerificaCor(atual->direita, 0, 0, CorFace(atual->direita))){
								Direita(ANTI, PARAMETROS);
								Tras(ANTI, PARAMETROS);
								Direita(HORARIO, PARAMETROS);
						}
				}

				atual = &vermelho;
				while(cont<4){

						if(VerificaCor(atual, 2, 0, BRANCO)){
								if(VerificaCor(atual->esquerda, 2, 2, CorFace(atual->esquerda))){
										Baixo(HORARIO, PARAMETROS);
										Esquerda(HORARIO, PARAMETROS);
										Baixo(ANTI, PARAMETROS);
										Esquerda(ANTI, PARAMETROS);
										encontrado = 1;
								}else if(VerificaCor(atual->esquerda, 2, 2, CorFace(atual->direita))){
										Baixo(HORARIO, PARAMETROS);
										Baixo(HORARIO, PARAMETROS);
										cont=0;
								}else{
										Baixo(ANTI, PARAMETROS);
										cont=0;
								}
						}
						if(VerificaCor(atual, 2, 2, BRANCO)){
								if(VerificaCor(atual->direita, 2, 0, CorFace(atual->direita))){
										Baixo(ANTI, PARAMETROS);
										Direita(ANTI, PARAMETROS);
										Baixo(HORARIO, PARAMETROS);
										Direita(HORARIO, PARAMETROS);
										encontrado = 1;
								}else if(VerificaCor(atual->direita, 2, 0, CorFace(atual->esquerda))){
										Baixo(ANTI, PARAMETROS);
										Baixo(ANTI, PARAMETROS);
										cont=0;
								}else{
										Baixo(HORARIO, PARAMETROS);
										cont=0;
								}
						}
						AvancaFace(atual, 4, ESQ);
						cont++;
				}

				cont=0;
				while(cont<4){
						if(VerificaCor(atual, 0, 0, BRANCO)){
										Frente(ANTI, PARAMETROS);
										Baixo(ANTI, PARAMETROS);
										Frente(HORARIO, PARAMETROS);
										encontrado=1;
										break;
						}
						if(VerificaCor(atual, 0, 2, BRANCO)){
										Frente(HORARIO, PARAMETROS);
										Baixo(HORARIO, PARAMETROS);
										Frente(ANTI, PARAMETROS);
										encontrado=1;
										break;
						}
						AvancaFace(atual, 4, ESQ);
						cont++;
				}

				if(!encontrado){

						atual = &amarelo;
						while(1){
									if(VerificaCor(atual, 0, 0, BRANCO)){
											if(VerificaCor(atual->oposto, 2, 0, BRANCO)){
								 					Frente(HORARIO, PARAMETROS);
								 					continue;
											}else{
													Esquerda(HORARIO, PARAMETROS);
													Frente(ANTI, PARAMETROS);
													Esquerda(ANTI, PARAMETROS);
													break;
											}
									}
									if(VerificaCor(atual, 0, 2, BRANCO)){
											if(VerificaCor(atual->oposto, 2, 2, BRANCO)){
								 					Frente(HORARIO, PARAMETROS);
								 					continue;
											}else{
													Direita(ANTI, PARAMETROS);
													Frente(HORARIO, PARAMETROS);
													Direita(HORARIO, PARAMETROS);
													break;
											}
									}
									if(VerificaCor(atual, 2, 0, BRANCO)){
											if(VerificaCor(atual->oposto, 0, 0, BRANCO)){
								 					Frente(HORARIO, PARAMETROS);
								 					continue;
											}else{
													Esquerda(ANTI, PARAMETROS);
													Frente(HORARIO, PARAMETROS);
													Esquerda(HORARIO, PARAMETROS);
													break;
											}
									}
									if(VerificaCor(atual, 2, 2, BRANCO)){
											if(VerificaCor(atual->oposto, 0, 2, BRANCO)){
								 					Frente(HORARIO, PARAMETROS);
								 					continue;
											}else{
													Direita(HORARIO, PARAMETROS);
													Frente(ANTI, PARAMETROS);
													Direita(ANTI, PARAMETROS);
													break;
											}
									}
							}
				}
		}

		//3º PASSO - 2 CAMADA
		writeDebugStreamLine("passo 3");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);

		atual = &vermelho;
		while(!Camada2(atual)){
				int encontrado=0;
				int cont=0;

				while(cont<4){
						if(!VerificaCor(atual, 2, 1, AMARELO)){
								switch(CorFace(atual)){
										case VERMELHO:
												if(!VerificaCor(atual->baixo, 1, 2, AMARELO))
														encontrado = 1;
												break;
										case AZUL:
												if(!VerificaCor(atual->baixo, 2, 1, AMARELO))
														encontrado = 1;
												break;
										case VERDE:
												if(!VerificaCor(atual->baixo, 0, 1, AMARELO))
														encontrado = 1;
												break;
										case LARANJA:
												if(!VerificaCor(atual->baixo, 1, 0, AMARELO))
														encontrado = 1;
												break;
								}
						}
						while(encontrado){
								if(VerificaCor(atual, 2, 1, CorFace(atual))){
										switch(CorFace(atual)){
												case VERMELHO:
														if(VerificaCor(atual->baixo, 1, 2, CorFace(atual->esquerda)))
																SequenciaCamada2(ESQ, PARAMETROS);
														else
																SequenciaCamada2(DIR, PARAMETROS);
														break;
												case AZUL:
														if(VerificaCor(atual->baixo, 2, 1, CorFace(atual->esquerda)))
																SequenciaCamada2(ESQ, PARAMETROS);
														else
																SequenciaCamada2(DIR, PARAMETROS);
														break;
												case VERDE:
														if(VerificaCor(atual->baixo, 0, 1, CorFace(atual->esquerda)))
																SequenciaCamada2(ESQ, PARAMETROS);
														else
																SequenciaCamada2(DIR, PARAMETROS);
														break;
												case LARANJA:
														if(VerificaCor(atual->baixo, 1, 0, CorFace(atual->esquerda)))
																SequenciaCamada2(ESQ, PARAMETROS);
														else
																SequenciaCamada2(DIR, PARAMETROS);
														break;
										}
										encontrado=0;
								}else{
										if(VerificaCor(atual, 2, 1, CorFace(atual->esquerda))){
												Baixo(ANTI, PARAMETROS);
												atual = atual->esquerda;
												continue;
										}else{
												if(VerificaCor(atual, 2, 1, CorFace(atual->direita))){
														Baixo(HORARIO, PARAMETROS);
														atual = atual->direita;
														continue;
												}else{
														Baixo(HORARIO, PARAMETROS);
														Baixo(HORARIO, PARAMETROS);
														atual = atual->oposto;
														continue;
												}
										}
								}
						}
						AvancaFace(atual, 4, ESQ);
						cont++;
				}
				cont = 0;
				while(cont<4){
						if(!VerificaCor(atual, 1, 0, CorFace(atual))){
								SequenciaCamada2(ESQ, PARAMETROS);
								break;
						}
						if(!VerificaCor(atual, 1, 2, CorFace(atual))){
								SequenciaCamada2(DIR, PARAMETROS);
								break;
						}
						AvancaFace(atual, 4, ESQ);
						cont++;
				}
	}


	//4 PASSO- CRUZ AMARELA
	writeDebugStreamLine("passo 4");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);
		atual = &vermelho;

		while(!Cruz(amarelo, AMARELO)){
				if(VerificaCor(atual, 2, 1, AMARELO)){
						if(!VerificaCor(atual->baixo, 0, 1, AMARELO) &&
							 !VerificaCor(atual->baixo, 1, 0, AMARELO) &&
							 !VerificaCor(atual->baixo, 2, 1, AMARELO) &&
							 !VerificaCor(atual->baixo, 1, 2, AMARELO)){
										SequenciaCruzAmarelo(PARAMETROS);
						}else{
								switch(CorFace(atual)){
											case VERMELHO:
													if(VerificaCor(atual->baixo, 2, 1, AMARELO))
															SequenciaCruzAmarelo(PARAMETROS);
													break;
											case AZUL:
													if(VerificaCor(atual->baixo, 1, 0, AMARELO))
															SequenciaCruzAmarelo(PARAMETROS);
													break;
											case VERDE:
													if(VerificaCor(atual->baixo, 1, 2, AMARELO))
															SequenciaCruzAmarelo(PARAMETROS);
													break;
											case LARANJA:
													if(VerificaCor(atual->baixo, 0, 1, AMARELO))
															SequenciaCruzAmarelo(PARAMETROS);
													break;
									}
						}
				}
				AvancaFace(atual, 4, ESQ);
		}

		//PASSO 5- CANTOS AMARELO
		writeDebugStreamLine("passo 6");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);
		atual = &vermelho;
		while(!Cantos(amarelo, AMARELO)){
				switch(QuantidadeCantos(amarelo, AMARELO)){
						case 0:
								SequenciaCantosAmarelo(PARAMETROS);
								break;
						case 1:
								switch(CorFace(atual)){
										case VERMELHO:
												if(VerificaCor(atual->baixo, 2, 2, AMARELO)){
														SequenciaCantosAmarelo(PARAMETROS);
												}
												break;
										case VERDE:
												if(VerificaCor(atual->baixo, 0, 2, AMARELO)){
														SequenciaCantosAmarelo(PARAMETROS);
												}
												break;
										case AZUL:
												if(VerificaCor(atual->baixo, 2, 0, AMARELO)){
														SequenciaCantosAmarelo(PARAMETROS);
												}
												break;
										case LARANJA:
												if(VerificaCor(atual->baixo, 0, 0, AMARELO)){
														SequenciaCantosAmarelo(PARAMETROS);
												}
												break;
								}
								break;
						case 2:
								if(VerificaCor(atual, 2, 2, AMARELO))
										SequenciaCantosAmarelo(PARAMETROS);
								break;
				}
				AvancaFace(atual, 4, ESQ);
		}

		//PASSO 6 - 3ª CAMADA CANTOS
		writeDebugStreamLine("passo 7");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);
		atual = &vermelho;
		cont = 0;
		while(!Camada3(atual)){
				if(VerificaCor(atual, 2, 0, atual->matriz[2][2])){
						if(VerificaCor(atual, 2, 0, CorFace(atual))){
								atual = atual->oposto;
								SequenciaL(PARAMETROS);
								if(VerificaCor(atual, 2, 0, CorFace(atual->esquerda))){
										Baixo(ANTI, PARAMETROS);
								}else if(VerificaCor(atual, 2, 0, CorFace(atual->direita))){
										Baixo(HORARIO, PARAMETROS);
								}else{
										Baixo(HORARIO, PARAMETROS);
										Baixo(HORARIO, PARAMETROS);
								}
								break; //
						}else{
								if(VerificaCor(atual, 2, 0, CorFace(atual->esquerda))){
										Baixo(ANTI, PARAMETROS);
								}else if(VerificaCor(atual, 2, 0, CorFace(atual->direita))){
										Baixo(HORARIO, PARAMETROS);
								}else{
										Baixo(HORARIO, PARAMETROS);
										Baixo(HORARIO, PARAMETROS);
								}
						}
				}else if(cont==4){
						SequenciaL(PARAMETROS);
						cont = 0;
				}else{
						AvancaFace(atual, 4, ESQ);
						cont++;
				}
		}

		cont=0;
		atual = &vermelho;
		while(cont<4){
				if(atual->matriz[2][0] == atual->matriz[2][1]){
						if(!VerificaCor(atual, 2, 1, CorFace(atual))){
								if(VerificaCor(atual, 2, 1, CorFace(atual->esquerda))){
										Baixo(ANTI, PARAMETROS);
								}else if(VerificaCor(atual, 2, 1, CorFace(atual->direita))){
										Baixo(HORARIO, PARAMETROS);
								}else{
										Baixo(HORARIO, PARAMETROS);
										Baixo(HORARIO, PARAMETROS);
								}
						}
				}
				AvancaFace(atual, 4, ESQ);
				cont++;
		}

		//ULTIMO PASSO
		writeDebugStreamLine("passo 8");
		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);

		atual = &vermelho;
		cont = 0;
		while(!MeiosIguais(atual)){
				if(VerificaCor(atual, 2, 1, CorFace(atual))){
								atual = atual->oposto;
								SequenciaTrocaFinal(PARAMETROS);
								break;
				}else if(cont==4){
						SequenciaTrocaFinal(PARAMETROS);
						cont = 0;
				}else{
						AvancaFace(atual, 4, ESQ);
						cont++;
				}
		}
		atual = &vermelho;

		if(!(atual->matriz[2][1] == CorFace(atual))){
				if(atual->esquerda->matriz[2][1] == CorFace(atual)){
						Baixo(HORARIO, PARAMETROS);
				}else if(atual->direita->matriz[2][1] == CorFace(atual)){
						Baixo(ANTI, PARAMETROS);
				}else{
						Baixo(HORARIO, PARAMETROS);
						Baixo(HORARIO, PARAMETROS);
				}
		}

		MostraTodasMatrizes(vermelho, laranja, verde, azul,branco, amarelo);
		EncerraEscritaLeitura(&arquivo);

		PermiteLeitura(&arquivo, movimentos);
		LerMovimento(&arquivo);
		EncerraEscritaLeitura(&arquivo);

		writeDebugStreamLine("Quantidade de movimentos = %d", total);

	Mover(FINAL, HORARIO, 1, 0);
		sleep(1000);
}


void mostraMatriz(int *matriz, string nome){
		int linha;
		int coluna;

		writeDebugStreamLine("%s", nome);
		for(linha=0; linha<=2; linha++){
				if(linha!=0)
						writeDebugStream("\n");
				for(coluna=0; coluna<=2; coluna++){
								writeDebugStream("%d\t", matriz[linha*3 + coluna]);
				}
		}
		writeDebugStream("\n\n");
}

int PertenceIntervalo(int menor, int maior, int numero){
		if(menor<=numero && numero<=maior){
				return 1;
		}else{
				return 0;
		}
}
void SalvaCor(face *atual, int linha, int coluna, int pos_peca){

		while(atual->matriz[linha][coluna]==VAZIO){
				atual->matriz[linha][coluna] = CapturaCor(pos_peca);
		}
}

void Scan(face *branco, face *amarelo, face *vermelho, face *laranja, face* azul, face* verde){

		//PRIMEIRA PARTE
		face *aux;
		int i;

		for(i=0; i<6; i++){
				switch(i){
						case 0:
								aux = azul;
								break;
						case 1:
								aux = amarelo;
								break;
						case 2:
								aux = verde;
								break;
						case 3:
								aux = branco;
								break;
						case 4:
								aux = vermelho;
								break;
						case 5:
								aux = laranja;
								break;
				}
				if(i==4){
						SalvaCor(branco, 0, 1, MEIO);
						Mover(GIRO, HORARIO, 1, 200);
				}
				if(i==5){
						Mover(FRENTE, HORARIO, 1, 0);
						Mover(GIRO, ANTI, 1, 200);
						SalvaCor(amarelo, 2, 1, MEIO);
						Mover(GIRO, HORARIO, 1, 200);
				}

				Mover(FRENTE, HORARIO, 1, 0);

				Mover(MEIO_GIRO, ANTI, 1, 600);
				SalvaCor(aux, 0, 2, CANTO_MAIOR);
				Mover(MEIO_GIRO, ANTI, 1, 600);
				SalvaCor(aux, 1, 2, MEIO);
				Mover(MEIO_GIRO, ANTI, 1, 600);
				SalvaCor(aux, 2, 2, CANTO_MAIOR);
				Mover(MEIO_GIRO, ANTI, 1, 600);
				if(i==4){
						SalvaCor(branco, 0, 1, MEIO);
				}
				if(i==0){
						SalvaCor(branco, 2, 1, MEIO);
				}
				if(i==5){
						Mover(FRENTE, ANTI, 1, 0);
						Mover(GIRO, ANTI, 1, 200);
						SalvaCor(amarelo, 0, 1, MEIO);
						Mover(GIRO, HORARIO, 1, 200);
				}
				Mover(FRENTE, ANTI, 1, 0);

				Mover(MEIO_GIRO, ANTI, 1, 600);
				SalvaCor(aux, 2, 0, CANTO_MEIO);
				Mover(MEIO_GIRO, ANTI, 1, 600);
				SalvaCor(aux, 1, 0, MEIO);
				Mover(MEIO_GIRO, ANTI, 1, 600);
				SalvaCor(aux, 0, 0, CANTO_MENOR);
				Mover(MEIO_GIRO, ANTI, 1, 600);
		}

		Mover(FRENTE, HORARIO, 1, 0);
		Mover(GIRO, HORARIO, 2, 200);
		Mover(FRENTE, ANTI, 1, 0);
	  Mover(GIRO, HORARIO, 1, 200);

		//SEGUNDA PARTE
		for(i=0; i<4; i++){
				switch(i){
						case 0:
								aux = vermelho;
								break;
						case 1:
								aux = verde;
								break;
						case 2:
								aux = laranja;
								break;
						case 3:
								aux = azul;
								break;
				}
				Mover(FRENTE, HORARIO, 1, 0);
				Mover(GIRO, HORARIO, 1, 200);
				Mover(FRENTE, HORARIO, 1, 0);
				Mover(GIRO, ANTI, 1, 200);
				if(i==1 || i==2){
						SalvaCor(aux, 2, 1, MEIO);
				}else{
						SalvaCor(aux, 0, 1, MEIO);
				}
				Mover(GIRO, ANTI, 1, 200);
				Mover(FRENTE, ANTI, 1, 0);
				Mover(GIRO, ANTI, 1, 200);
				if(i==1 || i==2){
						SalvaCor(aux, 0, 1, MEIO);
				}else{
						SalvaCor(aux, 2, 1, MEIO);
				}
				Mover(GIRO, ANTI, 1, 200);

				Mover(FRENTE, ANTI, 1, 0);
				Mover(GIRO, ANTI, 2, 200);
				Mover(FRENTE, HORARIO, 1, 0);
				Mover(GIRO, HORARIO, 1, 200);
				Mover(FRENTE, ANTI, 1, 0);
				Mover(GIRO, HORARIO, 1, 200);
				sleep(600);
		}
}

void Mover(char tipo, int sentido, int quantidade, int sleep_time){
		int i;

		for(i=0; i<quantidade; i++){
				switch (tipo){
						case FINAL:
								moveMotorTarget(base, 1080, 10*sentido);
								waitUntilMotorStop(base);
								sleep(sleep_time);
								break;
						case GIRO:
								moveMotorTarget(base, ANGULO_GIRO, 40*sentido);
								waitUntilMotorStop(base);
								sleep(sleep_time);
								break;
						case MEIO_GIRO:
								moveMotorTarget(base, ANGULO_GIRO/2, 20*sentido);
								waitUntilMotorStop(base);
								sleep(sleep_time);
								break;
						case FRENTE:
								setMotorTarget(frente, INCLINACAO_FRENTE_INICIAL*sentido, VELOCIDADE);
								waitUntilMotorStop(frente);

								setMotorTarget(pistao, DISTANCIA_PISTAO+7, VELOCIDADE);
								waitUntilMotorStop(pistao);


								if(sentido==-1){
										setMotorTarget(frente, (INCLINACAO_FRENTE_FINAL+8.5)*(sentido*-1), VELOCIDADE);
										waitUntilMotorStop(frente);
										sleep(sleep_time);

										setMotorTarget(pistao, POSICAO_INICIAL+2, VELOCIDADE);
										waitUntilMotorStop(pistao);
										sleep(sleep_time);

										setMotorTarget(frente, POSICAO_INICIAL+0.5, VELOCIDADE);
										waitUntilMotorStop(frente);
										sleep(sleep_time);
										break;
								}else{
										setMotorTarget(frente, (INCLINACAO_FRENTE_FINAL+2.8)*(sentido*-1), VELOCIDADE);
										waitUntilMotorStop(frente);
										sleep(sleep_time);

										setMotorTarget(pistao, POSICAO_INICIAL+2, VELOCIDADE);
										waitUntilMotorStop(pistao);
										sleep(sleep_time);

										setMotorTarget(frente, POSICAO_INICIAL+1.0, VELOCIDADE);
										waitUntilMotorStop(frente);
										sleep(sleep_time);
										break;
								}

						case BAIXO:
								setMotorTarget(pistao, DISTANCIA_PISTAO-5.8, VELOCIDADE);
								waitUntilMotorStop(pistao);
								sleep(sleep_time);

								moveMotorTarget(base, ANGULO_GIRO, VELOCIDADE*sentido);
								waitUntilMotorStop(base);

								setMotorTarget(pistao, POSICAO_INICIAL+2.5, VELOCIDADE);
								waitUntilMotorStop(pistao);
								sleep(sleep_time);
								break;

				}
		}
}

int CapturaCor(int posicao_peca){

		long red;
		long green;
		long blue;
		long cor;
		long sat;

		cor = getColorHue(sensor_cor);
		sat = getColorSaturation(sensor_cor);
		getColorRGB(sensor_cor, red, green, blue);

		if(posicao_peca == MEIO){

				if (PertenceIntervalo(90, 155, cor)){
						if(PertenceIntervalo(0, 18, sat)
								return AMARELO;
						if(PertenceIntervalo(19, 28, sat)){
							if(cor<100)
							return AMARELO;
						}
						return LARANJA;
				}

				if (PertenceIntervalo(75, 89, cor)){
						if(sat<=30)
							return AMARELO;
						else
							return BRANCO;
				}

				if (PertenceIntervalo(0, 20, cor)
						return VERMELHO;

				if (PertenceIntervalo(175, 190, cor)
						if(sat>60)
								return AZUL;

				if (PertenceIntervalo(164, 173, cor)
						if(sat>60)
								return VERDE;

				return VAZIO;
		}else{
				if (PertenceIntervalo(65, 115, cor)){
						if(PertenceIntervalo(0, 20, sat)
								return AMARELO;
						if(PertenceIntervalo(21, 52, sat)
								return BRANCO;
				}

				if (PertenceIntervalo(0, 26, sat)){
						if(PertenceIntervalo(23, 26, sat)){
								if(green>=47|| cor<=158){ //50
										return LARANJA;
								}else{
										return AMARELO;
								}
						}
						if(sat==17){
								return VAZIO;
						}else if(PertenceIntervalo(16, 22, sat)){//19
								if(cor>=170){
										if(red>=54)
												return LARANJA;
										else
												return AMARELO;
								}
								if(cor<170){ //38 cor<=160
										if(red>=45)
												return LARANJA;
										else
												return AMARELO;
								}
						}
						return AMARELO;
				}

				if (PertenceIntervalo(0, 40, sat)
						return LARANJA;

				if (PertenceIntervalo(0, 20, cor)
						return VERMELHO;

				if (PertenceIntervalo(171, 190, cor)){ //azul
						if (PertenceIntervalo(0, 18, sat)
								return AMARELO;
						if (PertenceIntervalo(19, 40, sat)
								return LARANJA;
						if(PertenceIntervalo(171, 180, cor)){
								if(PertenceIntervalo(0, 21, green) &&
									(PertenceIntervalo(0, 21, blue))
									return AZUL;
								else
									return VERDE;
						}
								return AZUL;
				}

				if (PertenceIntervalo(162, 179, cor)){ //verde
						if (PertenceIntervalo(0, 18, sat)
								return AMARELO;

						else if (PertenceIntervalo(19, 30, sat)
								return LARANJA;
						else
								return VERDE;
				}

				return VAZIO;
		}
}

void InicializarMotores(){
		resetMotorEncoder(motorA);
		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);

		setMotorBrakeMode(motorA, motorBrake);
		setMotorBrakeMode(motorB, motorBrake);
		setMotorBrakeMode(motorC, motorBrake);
}
